### ISSUE TITLE
make cloud.google.com work

### ISSUE THREAD

**Issue by shoenig** [modprox/modprox-proxy#8]
is probably another go-get redirect

```
2018/09/03 21:26:06 TRACE [fs-index] looking up revinfo at path /tmp/modprox-modules/cloud.google.com/go/v0.26.0.info
2018/09/03 21:26:06 ERROR [fs-index] failed to open revinfo file at /tmp/modprox-modules/cloud.google.com/go/v0.26.0.info
2018/09/03 21:26:06 TRACE [go-get-transform] domain cloud.google.com is not set for go-get redirects
2018/09/03 21:26:06 TRACE [redirect-transform] original: ["https" "cloud.google.com" [go] "v0.26.0" "" false]
2018/09/03 21:26:06 TRACE [redirect-transform] modified: ["https" "cloud.google.com" [go] "v0.26.0" "" false]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x678cc1]

goroutine 5 [running]:
github.com/modprox/libmodprox/upstream.(*SetPathTransform).Modify(0xc00000c960, 0xc00015ac00, 0xc00015ac00)
	/home/hoenig/Documents/go/src/github.com/modprox/libmodprox/upstream/transformer.go:313 +0x61
github.com/modprox/libmodprox/upstream.(*resolver).Resolve(0xc00000c980, 0xc000378f40, 0x13, 0xc000128598, 0x7, 0x35, 0xc00044a330, 0x28)
	/home/hoenig/Documents/go/src/github.com/modprox/libmodprox/upstream/transformer.go:44 +0xb4
github.com/modprox/modprox-proxy/internal/modules/background.(*reloadWorker).download(0xc00010ad20, 0xc000378f40, 0x13, 0xc000128598, 0x7, 0x0, 0xc000017b90)
```

**Comment by shoenig** [comment]
Added all of:
```
google.golang.org
cloud.google.com
contrib.go.opencensus.io
go.uber.org
```
to the internal list of known public go-get redirectors.
